version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ../:/workspace:cached
      - meeting-assistant-node-modules:/workspace/frontend/node_modules
      - meeting-assistant-python-packages:/usr/lib/python3.11/site-packages
      - meeting-assistant-data:/workspace/data
      
    # Overrides default command so things don't shut down after the process ends
    command: sleep infinity
    
    # Run as vscode user
    user: vscode
    
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally
    # (Adding the "ports" property to this file will not forward from a Codespace)
    
    environment:
      - NODE_ENV=development
      - PYTHONPATH=/workspace/backend
      - PYTHONUNBUFFERED=1
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000

  # PostgreSQL database (optional - can be enabled if needed)
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: meeting_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - database

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    profiles:
      - cache

  # Jupyter Lab for AI/ML development (optional)
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ../:/workspace:cached
      - jupyter-data:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=meeting-assistant-dev
    profiles:
      - jupyter

volumes:
  meeting-assistant-node-modules:
  meeting-assistant-python-packages:
  meeting-assistant-data:
  postgres-data:
  redis-data:
  jupyter-data:
